CREATE USER IF NOT EXISTS 'exporter'@'%' IDENTIFIED BY 'exporterpass'
  WITH MAX_USER_CONNECTIONS 3;
GRANT PROCESS, REPLICATION CLIENT, SLAVE MONITOR, SELECT ON *.* TO 'exporter'@'%';
FLUSH PRIVILEGES;
